---
- name: Triggering ec2 role
  hosts: localhost
  become: yes

  environment:
    anisble_ssh_private_key_file: ~/.ssh/ansible_key.pem
    host_key_checking: false
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  vars:
    mongo_uri: "{{ lookup('env', 'MONGO_URI')}}"
    port: "{{ lookup('env', 'PORT') }}"
    ansible_user: "ec2-user"
    key: "{{ lookup('env', 'key') }}"

  roles:
    - ec2_launch
